config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :trip_groups, :only => [:show], :as => :trips

  map.connect "win", :controller => 'web', :action => 'win'
  map.connect "cheap-train-tickets", :controller => 'web', :action => 'cheap_train_tickets'
  map.connect "trip/search", :controller => 'trip', :action => 'search'
  map.connect "payment_notification/create", :controller => "payment_notification", :action => "create", :conditions => { :method => :post }
  map.connect "payment_notification/complete_payment", :controller => "payment_notification", :action => "complete_payment", :conditions => { :method => :post }

  map.resource :basket
  map.resources :university_contacts
  map.resources :newsletter_sign_ups
  map.resources :universities, :only => [:show]
  map.resources :feedbacks, :only => [:create]

  # See how all your routes lay out with "rake routes"

  # Install the default routes as the lowest priority.
  map.connect '/image/dialog', :controller => 'image', :action => 'dialog'
  map.connect '/image/upload', :controller => 'image', :action => 'upload'
  map.connect '/image/insert/:id', :controller => 'image', :action => 'insert'
  map.connect '/image/:id/:width/:height', :controller => 'image', :action => 'index', :width => 0, :height => 0
  map.connect '/admin', :controller => 'login', :action => 'home'
  map.connect ':controller/:action'
  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'


  map.connect 'splash_page/:id', :controller => 'splash_page', :action => 'show'
  map.connect 'splash_page/redeem/:id', :controller => 'splash_page', :action => 'redeem'
  map.root :controller => "web"

  #this isn't great
  map.connect ':id', :controller => 'universities', :action => 'show'

end

app/models/trip.rb
class Trip < ActiveRecord::Base

  has_many :trip_flags, :dependent => :destroy
  accepts_nested_attributes_for :trip_flags, :reject_if => lambda{|a| a[:country_code].blank? }, :allow_destroy => true

  include ActionView::Helpers::NumberHelper
  include Tp2Mixin
  include TimeStampable
  include ImageHolder
  include DocumentHolder
  include Taggable

  attr_accessor :delete_document, :delete_photo_1, :delete_photo_2, :delete_photo_3, :delete_photo_4

  belongs_to :promoted_trip, :class_name => "Trip"
  belongs_to :trip_group
  has_many :photos
  has_many :reviews
  has_many :videos
  has_many :trip_instances
  has_many :rooms
  has_and_belongs_to_many :destinations
  has_and_belongs_to_many :accommodations
  has_and_belongs_to_many :activities
  has_and_belongs_to_many :products
  has_many :pickup_dropoff_times, :dependent => :destroy
  accepts_nested_attributes_for :pickup_dropoff_times, :reject_if => lambda{|a| a[:pickup_id].blank? }, :allow_destroy => true
  has_many :pickups, :through => :pickup_dropoff_times
  has_many :trip_ownerships, :dependent => :destroy
  has_many :universities, :through => :trip_ownerships

  has_many :day_itineraries
  has_many :booking_items
  has_many :basket_items
  has_many :cancelled_booking_items
  has_many :day_itineraries, :order => :day, :dependent => :destroy

  has_attached_file :document
  has_attached_file :photo_1
  has_attached_file :photo_2
  has_attached_file :photo_3
  has_attached_file :photo_4

  validates_presence_of :name, :start_date, :end_date, :student_price, :adult_price, :upgrade_price
  validates_numericality_of :student_price, :greater_than => 0
  validates_numericality_of :adult_price, :greater_than => 0
  validates_presence_of :summary, :on => :update
  validates_presence_of :itinerary, :on => :update
  validates_numericality_of :group_booking_count, :greater_than => 0, :only_integer => true
  validates_numericality_of :bookable_places, :greater_than => 0, :only_integer => true, :if => Proc.new{|x| x.bookable_places? }
  validates_numericality_of :group_booking_percentage, :greater_than => 0, :only_integer => true
  validates_presence_of :bookable_places, :if => Proc.new{|x| x.no_rooms? }
  validates_numericality_of :deposit_price, :greater_than_or_equal_to => 0

  validate :trip_has_destination, :on => :create

  named_scope :active, :conditions => ["display = 1"]
  named_scope :past, :conditions => ["end_date < ?", Date.today]
  named_scope :future, :conditions => ["start_date >= ?", Date.today], :order => "start_date"
  named_scope :on_list, lambda{ { :conditions => ["display=? AND start_date>=? AND highlight = ?", true, Date.today, true], :order => 'start_date asc' } }

  before_save :check_delete_document, :check_delete_photos, :calculate_length
  after_validation :set_video_embed_width_and_height

  def set_video_embed_width_and_height
    self.youtube_embed_code.gsub!(/width="\d*"/, 'width="900"').gsub!(/height="\d*"/, 'height="450"') unless youtube_embed_code.blank?
  end

  def self.categories
    ["Semester 1", "Christmas & New Year", "Semester 2", "Easter", "Summer"]
  end

  def check_delete_document
    if delete_document == "1"
      self.document = nil
    end
  end

  def check_delete_photos
    if delete_photo_1 == "1"
      self.photo_1.destroy
    end
    if delete_photo_2 == "1"
      self.photo_2.destroy
    end
    if delete_photo_3 == "1"
      self.photo_3.destroy
    end
    if delete_photo_4 == "1"
      self.photo_4.destroy
    end
  end

  def calculate_length
    self.length = ((self.end_date - self.start_date) + 1).to_i
  end

  def trip_has_destination
    errors.add('Destination', 'required') if self.destinations.length < 1
  end

  def before_create
    self.display = 0
  end

  def upgrade?
    upgrade_price > 0 ? true : false
  end

  def self.upcoming(limit = 2)
    self.find(:all, :conditions => ['display=true AND start_date >= ?', Date.today], :order => 'start_date', :limit => limit)
  end

  def picture
    if self.has_picture1?
      self.picture1
    else
      nil
    end
  end

  def comment
    comments = []
    self.destinations.each do |destination|
      destination.trips.each do |trip|
        trip.reviews.each{|c| comments << c}
      end
    end
    comments.sort_by{rand}.first
  end

  def pickup_time(pickup_id)
    pickup_time = self.pickup_dropoff_times.select{|x| x.pickup_id == pickup_id}.collect{|x| x.pickup_time}
  end

  def dropoff_time(pickup_id)
    dropoff_time = self.pickup_dropoff_times.select{|x| x.pickup_id == pickup_id}.collect{|x| x.dropoff_time}
  end

  def pickup_ids=(pickup_ids)
    # collect the ones which need to be destroyed
    self.pickup_dropoff_times.each do |pickup_dropoff_time|
      pickup_dropoff_time.destroy unless pickup_ids.include? pickup_dropoff_time.pickup_id
    end
    pickup_ids.each do |pickup_id|
      self.pickup_dropoff_times.create(:pickup_id => pickup_id) unless self.pickup_dropoff_times.any? { |d| d.pickup_id == pickup_id }
    end
  end

  def self.empty?
    self.count.zero?
  end

  def self.next
    Trip.find(:first, :conditions => ["display=1 AND start_date >= ?", Date.today], :order=>"start_date ASC")
  end

  def default_itinerary
    default_itinerary = self.destination.itinerary
    100.times do |number|
      default_itinerary.gsub!("DAY#{number}", (self.start_date + number).to_s)
    end
    default_itinerary
  end

  def length
    ((self.end_date - self.start_date) + 1).to_i
  end

  def day_trip?
    length == 1
  end

  def overnight_trip?
    length == 2
  end

  def multinight_trip?
    length > 2
  end


  def dates
    if start_date != end_date
      "#{self.start_date.strftime('%a %d %b %Y')} - #{self.end_date.strftime('%a %d %b %Y')}"
    else
      start_date.strftime('%a %d %b %Y')
    end
  end

  def length_dates
    if start_date != end_date
      "#{self.length} Days, #{self.start_date.strftime('%a %d %b %Y')} - #{self.end_date.strftime('%a %d %b %Y')}"
    else
      "1 Day, #{start_date.strftime('%a %d %b %Y')}"
    end

  end

  def pricef
    "&pound;#{sprintf('%.2f', self.price)}"
  end

  def upgrade_pricef
    "&pound;#{sprintf('%.2f', self.upgrade_price)}"
  end

  def destination_name_dates
    "#{self.name} - #{self.dates}"
  end

  def name_dates
    "#{self.name} - #{self.dates}"
  end

  def valid_basket_items
    self.basket_items.select{|x| x.basket && x.basket.expiry_time && x.basket.expiry_time > Time.now}
  end

  def rooms_configurations
      #require 'system_timer'
      require 'timeout'
      working_configurations = []
      begin

      Timeout::timeout(10) do
      #SystemTimer.timeout(10.seconds) do

        # add existing bookings
        males = booking_items.select{|x| x.gender == "Male"}.length
        females = booking_items.select{|x| x.gender == "Female"}.length

        total = males + females

        rooms = self.rooms.collect{|x| x.places}
        original_rooms = rooms.dup
        total_places = rooms.sum
        men_combs = []

        for i in 1..[rooms.length, males].min
          men_combs += rooms.combination(i).to_a.select{|x| (x.reduce(:+) >= males) && (females <= (total_places - x.reduce(:+)) )}.uniq
        end

        # for each of the possible male combinations
        for men_comb in men_combs

          # see what rooms are left
          rooms_left = original_rooms.dup
          for men_room in men_comb
            rooms_left.delete_at(rooms_left.index(men_room))
          end

          women_combs = []
          for i in 1..[rooms_left.length, females].min
            women_combs += rooms_left.combination(i).to_a.select{|x| (x.reduce(:+) >= females)}.uniq
          end

          for women_comb in women_combs

            comb_out = []

            # for each of the mens rooms in this combination
            for men_room in men_comb
              # make male room
              comb_out << "#{men_room}m"
            end

            # for each of the womens rooms in this combination
            for women_room in women_comb
              # make female room
              comb_out << "#{women_room}f"
            end

            # make a note of empty rooms
            rooms_left = original_rooms.dup
            for room in comb_out
              rooms_left.delete_at(rooms_left.index(room.to_s.gsub(/\D/, "").to_i))
            end

            for neut_room in rooms_left
              comb_out << neut_room
            end
            working_configurations << comb_out
            return working_configurations if self.rooms.length > 15 && working_configurations.length >= 3
          end

        end
      end
      rescue Exception => e
        logger.info e.message
        #logger.info e.backtrace.inspect
      end
      return working_configurations
  end

  def working_configurations
    wc = []
    for number in (0..places)
      m = number
      f = places-number
      wc << [m,f] if bookable?(m,f)
    end
    return wc
  end

  def total_places
    total = 0
    room_places = rooms.map{|x| x.places}.sum || 0
    if bookable_places != nil
      if bookable_places <= room_places || no_rooms?
        total = bookable_places
      else
        total = room_places
      end
    else
      total = rooms.map{|x| x.places}.sum
    end
    return total
  end

  def places
    ret = total_places
    ret -= booking_items.length
    ret -= valid_basket_items.length
    return ret
  end

  def sold_out?
    places < 1
  end

  def price(buyer_type)
    if buyer_type == "Student"
      if early_early_bird?
        new_price = student_price - early_bird_1_amount_off
      elsif early_bird?
        new_price = student_price - early_bird_2_amount_off
      else
        new_price = student_price - (10.0 * (student_price/100.00))
      end
    else
      if early_early_bird?
        new_price = adult_price - early_bird_1_amount_off
      elsif early_bird?
        new_price = adult_price - early_bird_2_amount_off
      else

app/views/basket/_basket_item_fields.html.erb
<%# encoding: UTF-8 %>

<tr class="<%= f.object.is_valid? ? "valid" : "invalid" %>">

<td style="color:<%= f.object.gender == "Male" ? "#000000" : "#000000" %>;">
  <strong><%= f.object.gender.titleize %></strong>
</td>

<td>
  <%= f.text_field :first_name, :class=>"short" %>
</td>

<td>
  <%= f.text_field :last_name, :class=>"short" %>
</td>

<td>
  <% options = options_for_select([["Student (Student ID required) - #{number_to_currency f.object.trip.price("Student"), :unit => "£"}", 'Student'],["Adult - #{number_to_currency f.object.trip.price("Adult"), :unit => "£"}", 'Adult']]) %>
  <%= f.select :buyer_type, options %>
</td>

<td>
  <% if f.object.trip.upgrade? %>
    <%= f.select :upgrade, [['No',false],["Yes - #{number_to_currency f.object.trip.upgrade_price, :unit => "£"}",true]] %>
  <% else %>
    n/a
  <% end %>
</td>

<td>
  <% pickup_dropoff_times = f.object.trip.pickup_dropoff_times.sort_by{|x| x.pickup_time}.reject{|x| x.places_left == 0} %>
  <p>
    <%= f.collection_select :pickup_dropoff_time_id, pickup_dropoff_times, :id, :name_pickup_time_dropoff_time_with_places_left, {:class => "radio", :multiple => false} %>
  </p>
</td>

<td>
  <%= f.check_box :_destroy, :class=>"checkbox" %>
</td>

</tr>

app/views/basket/_booking_steps.html.erb
<!-- 
  <a href="#" class="highlight"><span>1</span>Places</a>
  <a href="#" class="ready"><span>2</span>Details</a>
  <div><span>3</span>Basket</div>
-->

<% if @current_basket && @current_basket.basket_items.length > 0 %>

  <div class="basket_checkout_navigation">
  
    <% if params[:controller] == "basket" && params[:action] == "bookings" %>      
      <%= link_to "<span>1</span>Details", {:controller => "basket", :action => "bookings"}, :class => "highlight" %>
    <% else %>
      <%= link_to "<span>1</span>Details", {:controller => "basket", :action => "bookings"}, :class => "ready" %>
    <% end %>
    
    <% if params[:controller] == "basket" && params[:action] == "show" %>      
      <%= link_to "<span>2</span>Basket", {:controller => "basket", :action => "show"}, :class => "highlight" %>
    <% else %>
      <%= link_to "<span>2</span>Basket", {:controller => "basket", :action => "show"}, :class => "ready" %>
    <% end %>
    
    <% if params[:controller] == "basket" && params[:action] == "extras" %>      
      <%= link_to "<span>3</span>Extras", {:controller => "basket", :action => "extras"}, :class => "highlight" %>
    <% elsif @current_basket.all_basket_items_valid? %>
      <%= link_to "<span>3</span>Extras", {:controller => "basket", :action => "extras"}, :class => "ready" %>
    <% else %>
      <div><span>3</span>Extras</div>
    <% end %>    
    
    <% if params[:controller] == "basket" && params[:action] == "confirm" %>      
      <%= link_to "<span>4</span>Confirmation", {:controller => "basket", :action => "confirm"}, :class => "highlight" %>
    <% elsif @current_basket.all_basket_items_valid? %>
      <%= link_to "<span>4</span>Confirmation", {:controller => "basket", :action => "confirm"}, :class => "ready" %>
    <% else %>
      <div><span>4</span>Confirmation</div>
    <% end %>    
    
    <% if params[:controller] == "basket" && params[:action] == "offline_payment_preview" %>
      <%= link_to "<span>5</span>Payment", {:controller => "basket", :action => "offline_payment_preview"}, :class => "highlight" %>
    <% else %>
      <div><span>5</span>Payment</div>
    <% end %>
    
  </div>
  <div class="clear" style="margin-bottom: 30px;"></div>

<% end %>

app/views/basket/_discount.html.erb
<% bpcnas = @current_basket.best_promo_code_name_and_saving %>
<tr>
<td colspan=2 valign="top">
<div align="right">

<% if bpcnas && bpcnas.last > 0 %>
<span class="red">Special Offer:</span><br />
<span class="discount_name"><%= bpcnas.first %></span>
</div>
<!--<p class="discount_offer">Make sure you check our <%= link_to "Special Offers", :controller=>"web", :action=>"special_offers" %> page to see if you can save even more money!</p>-->
</td>
<td valign="top" class="red">-<%= number_to_currency(bpcnas.last, :unit => "&pound;") %></td>
</tr>

<% else -%>
<!--<p class="discount_offer">Make sure you check our <%= link_to "Special Offers", :controller=>"web", :action=>"special_offers" %> page to see if you can save money!</p>-->
</div>
</td>
<td valign="top" class="red">-<%= number_to_currency(0, :unit => "&pound;") %></td>
</tr>

<% end -%>

app/views/basket/_expire.html.erb
<div class="message">
We will reserve your places until <u><%= @current_basket.expiry_time.strftime("%H:%M") %></u>, please try and complete your order as soon as possible.
</div>

app/views/basket/_extra_basket_item_fields.html.erb
<% trip = f.object.trip %>

<% if trip.products.length > 0 %>

  <fieldset>
  <legend>Extras</legend>

  <% for product in trip.products %>
    <p>
      <%= check_box_tag "basket_item[product_ids][]", product.id, f.object.products.include?(product), {:class => "checkbox"} %>
      <%= product.name %> - <%= number_to_currency product.price, :unit => "&pound;" %>
      <br />
      <%= product.summary %>
      <% if product.has_picture1? %>
        <br /><%= scale_image_tag product.picture1, :width => 80, :height => 80 %>
      <% end %>
    </p>
  <% end %>

  </fieldset>

<% end %>

app/views/basket/book.html.erb
<% @page_title = @trip.name %>

<script type="text/javascript">
function user_feedback()
{
  $('wait').toggle();
  $('spinner').toggle();
  $('submit_none').toggle();
}
</script>
<% hide_flash %>
<%= render "booking_steps" %>

<h1>How many places would you like to book on this trip?</h1>
<h2><%= @trip.name %></h2>
<h3>
  <%= @trip.pretty_student_price %> *
  <br />
  <%= @trip.pretty_adult_price %> *
</h3>
<p><span  class="date_highlight"><%= @trip.length_dates %></span></p>

<% if flash[:error] %>
  <div id="flash_error">
  <%= flash[:error] %>
  <p>
  <% if @trip.no_rooms? %>
    <%= @trip.places %>
  <% end %>
  </p>
  </div>
<% end %>

<% form_tag :action => "book_post" do %>

  <%= hidden_field_tag :trip_id, params[:trip_id] %>
  <p>
    <%= label_tag "male_bookings", "How many men are you booking on this trip?", :class=>"none" %>
    <%= select_tag :male_bookings, options_for_select((0..20), params[:male_bookings].to_i) %>
  </p>
  <p>
    <%= label_tag "female_bookings", "How many women are you booking on this trip?", :class=>"none" %>
    <%= select_tag :female_bookings, options_for_select((0..20), params[:female_bookings].to_i) %>
  </p>

  <p>
    <br />
    * Please note that a <%= booking_fee %>&#37; booking fee is applicable. There are no other transaction charges.
    <br /><br />
  </p>

  <p>
    <%= submit_tag "BOOK NOW", :class => "submit_none", :id => "submit_none", :onclick => "user_feedback()" %>
  </p>

  <div id="spinner" style="display: none;"><%= image_tag("/images/loading-spinner.gif") %></div>
  <p id="wait" style="display: none;">Please wait while we calculate room availability and combinations...</p>
  <div class="clear"></div>


<% end %>

<%= render :partial => 'web/payment_types' %>

<% hide_right %>

app/views/basket/booking.html.erb
<h1><%= @page_title = "Edit Bookings" %></h1>

<%- flash.each do |name, msg| -%>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<%- end -%>

<% form_for @basket_item, :url => {:controller => "basket", :action => "booking", :id => @basket_item.id}, :html => {:method => "post"} do |f| %>

  <%= f.error_messages :header_message => nil, :message => "Opps... looks like there was a problem with the information you entered", :id => "flash_error" %>

  <%= render "basket_item_fields", :f => f %>

  <%= render "extra_basket_item_fields", :f => f %>

  <%= f.submit "Submit" %>

<% end %>

app/views/basket/bookings.html.erb
<% hide_right %>
<% hide_flash %>

<%= render "booking_steps" %>
<h1><%= @page_title = "Add Your Bookings" %></h1>


<%= render "basket/expire" %>

<%- flash.each do |name, msg| -%>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<%- end -%>

<% form_for @basket, :url => {:controller => "basket", :action => "bookings"}, :html => {:method => "post"} do |f| %>

<%= f.error_messages :header_message => nil, :message => "Opps... looks like there was a problem with the information you entered", :id => "flash_error" %>

<p>
  <small>* denotes a required field, please enter a first name and family name for each person in your bookings.</small>
</p>


<table>

  <tr>
    <th>Gender</th>
    <th>*First Name</th>
    <th>*Family Name</th>
    <th>*Type</th>
    <th>Upgrade</th>
    <th>*Pickup &amp; Dropoff Point</th>
    <th>Delete</th>
  </tr>

<% for trip in @basket.trips %>
  <tr>
    <td colspan="4"><%= trip.name_dates %></td>
    <td colspan="3"><%= trip.format_upgrade_description %></td>
  </tr>
  <% f.fields_for :basket_items, @basket.basket_items.select{|x| x.trip == trip }.sort_by{|x| x.created_at }.reverse do |builder| %>
    <%= render "basket_item_fields", :f => builder %>
  <% end %>
<% end %>

</table>

<%= f.submit "CONTINUE YOUR BOOKING", :class=>"submit_none" %>

<% end %>

<br />
<hr />
<h2>Pickup &amp; Dropoff Point Details</h2>
<% for trip in @basket.trips %>
  <h3><%= trip.name_dates %></h3>
  <p>
  <% for pickup_dropoff_time in trip.pickup_dropoff_times.sort_by{|x| x.pickup_time} %>
    <%= pickup_dropoff_time.name_pickup_time_dropoff_time %>
    <% if pickup_dropoff_time.pickup.map_code && pickup_dropoff_time.pickup.map_code.strip != '' %>
      <span class="small">[ <%= link_to("view map", pickup_dropoff_time.pickup.map_code, :popup => [pickup_dropoff_time.pickup.name, 'height=600,width=600']) %> ]</span>
    <% end %>
    <br />
  <% end %>
  </p>
<% end %>

app/views/basket/confirm.html.erb
<%= render "booking_steps" %>
<h1><%= @page_title = "Confirm Order" %></h1>

<%- flash.each do |name, msg| -%>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<%- end -%>

<% if @current_basket.basket_items.length < 1 %>
  Sorry, there are currently no items in your basket.  You can see our upcoming trips <%= link_to "here", :controller => "trip" %>
<% else %>

  <table>

  <% for trip in @trips %>

    <tr>
      <th colspan=3><%= trip.name %> Bookings</th>
    </tr>

    <% for basket_item in @current_basket.basket_items.select{|x| x.trip == trip} %>
      <%= render "basket_item/basket_item_advanced", :basket_item => basket_item %>
    <% end %>

  <% end %>

  <tr>
  <td colspan=2><div align="right">Trips Subtotal</div></td>
  <td><%= number_to_currency(@current_basket.basket_items_total, :unit => "&pound;") %></td>
  </tr>

  <tr>
  <td colspan=2><div align="right">Booking Fee</div></td>
  <td><%= number_to_currency(@current_basket.booking_fee, :unit => "&pound;") %></td>
  </tr>

  <%= render 'discount' %>

  <tr>
  <td colspan=2><div align="right"><strong>Total</strong></div></td>
  <td><strong><%= number_to_currency(@current_basket.total, :unit => "&pound;") %></strong></td>
  </tr>

  <% if @current_basket.deposit? %>
    <tr>
    <td colspan=2><div align="right"><strong>Total To Pay Now (Deposit)</strong></div></td>
    <td><strong><%= number_to_currency(@current_basket.deposit_total, :unit => "&pound;") %></strong></td>
    </tr>
  <% end %>

  </table>

<% if @current_basket.all_basket_items_valid? %>
  <% form_tag({:action => "payment_confirm"}, :html => {:method => :post}) do %>

    <p>
      <%= check_box_tag :terms_and_conditions, "1", false, :required => true, :class=>"checkbox"  %>
      I agree to the <%= link_to 'terms and conditions', {:controller => :web, :action => :terms}, :popup => true %>
    </p>

    <br />
    <% if @current_basket.total == 0 %>
      <%= submit_tag "CONFIRM ORDER", :name => "free", :class=>"submit_none" %>
    <% else %>
      <p>
        <%= submit_tag "CARD PAYMENT", :name => "card", :class=>"submit_none", :onclick => "ga('send', { 'hitType': 'pageview', 'page': 'http://www.dontbeatourist.co.uk/proceeded-to-paypal-payment', 'title': 'Proceeded to paypal payment' });" %> <%= submit_tag "CASH PAYMENT", :name => "cash", :class=>"submit_none" %>
      </p>
    <% end %>

    <% if session[:admin_id] && Admin.exists?(session[:admin_id]) %>
      <%= submit_tag "Admin", :name => "admin", :class=>"submit_none"  %>
    <% end %>

  <% end %>

<% end %>

<%= render :partial => 'web/payment_types' %>

<% end %>


<% content_for :right do %>
   <!--<div class="advert_3">
    <%= link_to "Find out more", {:controller => "web", :action => "special_offers"}, {:class=>"advert_more"} %>
  </div>-->
  <%= render :partial => 'web/right_bookings' %>
<% end %>

app/views/basket/extras.html.erb
<% hide_right %>

<% form_tag :action => "set_extras" do %>

<p>
  <%= submit_tag "CONTINUE BOOKING", :class=>"submit" %>
</p>

<%= render "booking_steps" %>
<h1><%= @page_title = "Add Extras" %></h1>

<%= render "basket/expire" %>



<%- flash.each do |name, msg| -%>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<%- end -%>
<br />
<% for product in @products %>
  <% if product.has_picture1? %>
    <%= scale_image_tag product.picture1, :width => 100, :style=>"margin: 6px 15px 5px 0px; float: left;" %>
  <% end %>
  <h3 style="margin-top: 0px; padding-top: 0px;"><%= product.name %></h3>
  <strong><%= number_to_currency product.price, :unit => "&pound;" %></strong>
  <%= product.summary %>
  <hr />

<% end %>
  <br />
  <table>
    <tr>
      <th>Name</th>
      <% for product in @products %>
        <th><%= product.name %></th>
      <% end %>
      <% for basket_item in @current_basket.basket_items %>
        <tr>
          <td><%= basket_item.first_name %> <%= basket_item.last_name %></td>
          <% for product in @products %>
            <td>
            <% if basket_item.trip.products.include? product %>
              <%= check_box_tag "basket_items[#{basket_item.id}][product_ids][#{product.id}]", "1", basket_item.products.include?(product), :class=>"checkbox" %>
            <% else %>
              -
            <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tr>
  </table>

  <p>
    <%= submit_tag "CONTINUE BOOKING", :class=>"submit" %>
  </p>
  <br />
  <br />

<% end %>

<%= render :partial => 'web/payment_types' %>

app/views/basket/part_payment.html.erb
<h1><%= @page_title = "Confirm Admin Payment" %></h1>

<% form_tag :html => {:method => :post} do %>

  <%- flash.each do |name, msg| -%>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <%- end -%>

  <p>
    Total Due: <%= number_to_currency @current_basket.total, :unit => "&pound;" %>
  </p>

  <p>
    <%= label_tag :amount, "Amount already paid" %><br />
    <%= text_field_tag :amount %>
  </p>

  <br />
  <p>
    <%= submit_tag "Place My Booking!", :class => "submit" %>
  </p>

<% end %>